include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    argument_type_not_assignable: false

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    lines_longer_than_80_chars: true
    always_put_required_named_parameters_first: false
    prefer_relative_imports: true
    constant_identifier_names: false
    avoid_void_async: false