name: kurika_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^3.1.0
  # State management
  flutter_bloc: ^3.1.0
  # Value equality
  equatable: ^1.0.3
  # Functional programming
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+4
  # Shared Preferences
  shared_preferences: ^0.5.6+1
  # Cupertino icons
  cupertino_icons: ^0.1.2
  # Google's Firebase Products
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  lint: ^1.1.1

flutter:

  uses-material-design: true