name: kurika_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:  
    sdk: flutter

  # State Management & Dependency Injection
  provider: ^4.0.4
  # Routes
  auto_route: ^0.3.0
  # Cupertino icons
  cupertino_icons: ^0.1.2
  # Google's Firebase Products
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  lint: ^1.1.1
  build_runner: ^1.7.4
  auto_route_generator: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - lang/
    - images/backgrounds/